# Generated by Django 2.0.6 on 2021-09-17 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('pk_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('pk_pet', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('race', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='petshop',
            fields=[
                ('pk_petshop', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('direction', models.TextField()),
                ('phone', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pet'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_petshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.petshop'),
        ),
    ]
