# Generated by Django 3.2.7 on 2021-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.URLField(default='https://st.depositphotos.com/1967477/1959/v/600/depositphotos_19591553-stock-illustration-cute-cat-cartoon.jpg', max_length=8000),
        ),
    ]
